language: php
php:
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - nightly

before_script:
  - composer install

script:
  - phpunit

after_script:
  - vendor/bin/test-reporter --coverage-report="test/coverage/clover.xml"

addons:
  code_climate:
    repo_token: 7e3fb2afbea05ceff69722d310116f41e2d00a07f813006e86b954b0cbd7cf8b